config/routes.rb
Basemail::Application.routes.draw do

  root 'home#new'
  resources 'home' do 
    collection do
      post 'create', as: 'create'
    end
  end

  

end

app/models/draft.rb
class Draft < ActiveRecord::Base

  has_attached_file :file,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :dropbox_options => {}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def new
    @draft = Draft.new
  end

  def create
    respond_to do |format|
      if params[:commit] == 'Send'
        if is_a_valid_email(params[:draft][:to])
          ActionMailer::Base.mail(:from => "yevgeny@example.com", :to => params[:draft][:to], :subject => params[:draft][:subject], :body => params[:draft][:body]).deliver      
          flash[:success] = t('email.success_sent')        
          format.html { redirect_to root_url }
          format.json
        else
          flash.now[:alert] = t('email.invalidate_recipient_email')        
          @draft = Draft.new
          format.html { render :new}
          format.json
        end
      elsif params[:commit] == 'Save as draft'
        @draft = Draft.new(draft_params)
        if @draft.save
          flash[:success] = t('email.success_saved_as_draft')
          format.html { redirect_to root_url }
          format.json          
        else          
          flash.now[:alert] = t('email.fail_sent')
          @draft = Draft.new
          format.html { render :new }
          format.json
        end
      else        
        @draft = Draft.new
        flash.now[:alert] = t('email.invalid_action')
        format.html { render :new }
        format.json
      end
    end
  end

  def is_a_valid_email(email)
    email_regex = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
    (email =~ email_regex)
  end

  private
  def draft_params
    params.require(:draft).permit(:to, :subject, :body, :file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1> Index Page </h1>

app/views/home/new.html.erb
<h1>
  Send Email
</h1>
<pre>
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>
</pre>

<%= form_for(@draft, url: create_home_index_url, :method=>'post') do |f| %>
  <div class="row">
    <div class="form-group">
      <%= f.label :to, 'To: ' %>
      <%= f.text_field :to, placeholder: 'example@test.com' %>    
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, :rows=>7 %>
    </div>
    <div class="form-group">
      <%= f.label :file %>
      <%= f.file_field :file %>
    </div>
    <hr/>
    <div class="form-actions">
      <%= f.submit 'Send' %>
      <%= f.submit 'Save as draft' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basemail</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>